spring.application.name=springstrater
server.port=8080
spring.datasource.url=jdbc:h2:file:./db/blogdb
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/db-console
spring.h2.console.settings.web-allow-others=false

spring.jpa.hibernate.ddl-auto=create-drop

#enable lazy loading
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

password-reset-token-expiry-minutes=600

# Email configuration
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.config.import=secret.properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.smtp.ssl.trust=sandbox.smtp.mailtrap.io
mail.transport.protocol=smtp

Site.Domain=http://localhost:8080

# Logging configuration
logging.level.org.studyeasy.springstrater=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging.file.name=logs/springstrater.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
